### ISSUE TITLE
Check error ENETUNREACH 

### ISSUE THREAD

**Issue by DiegoRampim** [netsmarttech/node-open-protocol#1]
- After this error the node not retry connection.
- This error is not treated.

```
30 Aug 17:25:47 - [info] Started flows
30 Aug 17:25:47 - [error] [op node:aa869f5d.ad70f] error on requestError: service unavailable
30 Aug 17:25:47 - [error] [op node:d52517aa.1a1018] error on requestError: service unavailable
30 Aug 17:25:47 - [error] [op node:d52517aa.1a1018] error on requestError: service unavailable
30 Aug 17:25:47 - [error] [op config:OP234] Error: connect ENETUNREACH 192.168.0.33:4545 - Local (0.0.0.0:0)
(node:3543) UnhandledPromiseRejectionWarning: Error: service unavailable
    at SessionControlClient.close (/home/guilherme/.node-red/node_modules/node-open-protocol/src/sessionControlClient.js:411:21)
    at OpenProtocolConfig.node.on (/home/guilherme/.node-red/node_modules/node-red-contrib-open-protocol/red/openProtocol.js:201:21)
    at OpenProtocolConfig.Node.close (/home/guilherme/test/red/node_modules/node-red/red/runtime/nodes/Node.js:102:22)
    at /home/guilherme/test/red/node_modules/node-red/red/runtime/nodes/flows/Flow.js:166:47
    at init (/home/guilherme/test/red/node_modules/when/lib/makePromise.js:39:5)
    at new Promise (/home/guilherme/test/red/node_modules/when/lib/makePromise.js:27:53)
    at Function.promise (/home/guilherme/test/red/node_modules/when/when.js:97:10)
    at /home/guilherme/test/red/node_modules/node-red/red/runtime/nodes/flows/Flow.js:163:38
    at init (/home/guilherme/test/red/node_modules/when/lib/makePromise.js:39:5)
    at new Promise (/home/guilherme/test/red/node_modules/when/lib/makePromise.js:27:53)
    at Function.promise (/home/guilherme/test/red/node_modules/when/when.js:97:10)
    at /home/guilherme/test/red/node_modules/node-red/red/runtime/nodes/flows/Flow.js:158:34
    at init (/home/guilherme/test/red/node_modules/when/lib/makePromise.js:39:5)
    at new Promise (/home/guilherme/test/red/node_modules/when/lib/makePromise.js:27:53)
    at Function.promise (/home/guilherme/test/red/node_modules/when/when.js:97:10)
    at Flow.stop (/home/guilherme/test/red/node_modules/node-red/red/runtime/nodes/flows/Flow.js:127:21)
(node:3543) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3543) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:3543) UnhandledPromiseRejectionWarning: Error: service unavailable
    at SessionControlClient.close (/home/guilherme/.node-red/node_modules/node-open-protocol/src/sessionControlClient.js:411:21)
    at OpenProtocolConfig.node.on (/home/guilherme/.node-red/node_modules/node-red-contrib-open-protocol/red/openProtocol.js:201:21)
    at OpenProtocolConfig.Node.close (/home/guilherme/test/red/node_modules/node-red/red/runtime/nodes/Node.js:102:22)
    at /home/guilherme/test/red/node_modules/node-red/red/runtime/nodes/flows/Flow.js:166:47
    at init (/home/guilherme/test/red/node_modules/when/lib/makePromise.js:39:5)
    at new Promise (/home/guilherme/test/red/node_modules/when/lib/makePromise.js:27:53)
    at Function.promise (/home/guilherme/test/red/node_modules/when/when.js:97:10)
    at /home/guilherme/test/red/node_modules/node-red/red/runtime/nodes/flows/Flow.js:163:38
    at init (/home/guilherme/test/red/node_modules/when/lib/makePromise.js:39:5)
    at new Promise (/home/guilherme/test/red/node_modules/when/lib/makePromise.js:27:53)
    at Function.promise (/home/guilherme/test/red/node_modules/when/when.js:97:10)
    at /home/guilherme/test/red/node_modules/node-red/red/runtime/nodes/flows/Flow.js:158:34
    at init (/home/guilherme/test/red/node_modules/when/lib/makePromise.js:39:5)
    at new Promise (/home/guilherme/test/red/node_modules/when/lib/makePromise.js:27:53)
    at Function.promise (/home/guilherme/test/red/node_modules/when/when.js:97:10)
    at Flow.stop (/home/guilherme/test/red/node_modules/node-red/red/runtime/nodes/flows/Flow.js:127:21)
(node:3543) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:3543) UnhandledPromiseRejectionWarning: Error: service unavailable
    at SessionControlClient.close (/home/guilherme/.node-red/node_modules/node-open-protocol/src/sessionControlClient.js:411:21)
    at OpenProtocolConfig.node.on (/home/guilherme/.node-red/node_modules/node-red-contrib-open-protocol/red/openProtocol.js:201:21)
    at OpenProtocolConfig.Node.close (/home/guilherme/test/red/node_modules/node-red/red/runtime/nodes/Node.js:102:22)
    at /home/guilherme/test/red/node_modules/node-red/red/runtime/nodes/flows/Flow.js:166:47
    at init (/home/guilherme/test/red/node_modules/when/lib/makePromise.js:39:5)
    at new Promise (/home/guilherme/test/red/node_modules/when/lib/makePromise.js:27:53)
    at Function.promise (/home/guilherme/test/red/node_modules/when/when.js:97:10)
    at /home/guilherme/test/red/node_modules/node-red/red/runtime/nodes/flows/Flow.js:163:38
    at init (/home/guilherme/test/red/node_modules/when/lib/makePromise.js:39:5)
    at new Promise (/home/guilherme/test/red/node_modules/when/lib/makePromise.js:27:53)
    at Function.promise (/home/guilherme/test/red/node_modules/when/when.js:97:10)
    at /home/guilherme/test/red/node_modules/node-red/red/runtime/nodes/flows/Flow.js:158:34
    at init (/home/guilherme/test/red/node_modules/when/lib/makePromise.js:39:5)
    at new Promise (/home/guilherme/test/red/node_modules/when/lib/makePromise.js:27:53)
    at Function.promise (/home/guilherme/test/red/node_modules/when/when.js:97:10)
    at Flow.stop (/home/guilherme/test/red/node_modules/node-red/red/runtime/nodes/flows/Flow.js:127:21)
```

**Comment by DiegoRampim** [comment]
Fix [Commit](https://github.com/netsmarttech/node-open-protocol/commit/95df513ce0ebac21360841658aceb8bf6ebe4613)
