### ISSUE TITLE
Controller internal request timeout

### ISSUE THREAD

**Issue by martybertrand** [netsmarttech/node-open-protocol#50]
Hello, I can't disconnect from the tool, MID0044 'disconnectTool'. I want to execute this command because when I launch 5 screwdriving commands everything works fine and when I send the 6th I have a busy protocol! So I don't know if this is the right method. It's my app that sends the data to my API, which makes the connection with the controller.

` Error: [Session Control Client] negative acknowledge, MID[44], Error[Controller internal request timeout]
    at SessionControlClient._receiverData (D:\wamp64\www\Projet_Paperless\api_modop_v2\node_modules\node-open-protocol-desoutter\src\sessionControlClient.js:1057:23)
    at SessionControlClient._onDataLinkLayer (D:\wamp64\www\Projet_Paperless\api_modop_v2\node_modules\node-open-protocol-desoutter\src\sessionControlClient.js:1000:14)
    at LinkLayer.<anonymous> (D:\wamp64\www\Projet_Paperless\api_modop_v2\node_modules\node-open-protocol-desoutter\src\sessionControlClient.js:363:51)
    at LinkLayer.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at LinkLayer._onDataMidParser (D:\wamp64\www\Projet_Paperless\api_modop_v2\node_modules\node-open-protocol-desoutter\src\linkLayer.js:326:19)
    at MIDParser.<anonymous> (D:\wamp64\www\Projet_Paperless\api_modop_v2\node_modules\node-open-protocol-desoutter\src\linkLayer.js:111:50)
    at MIDParser.emit (node:events:514:28)`
    
    Some functions of my code:
    
   ``` 
let options = {};

const connectToServer = (ip, port, pset, number_screw) => {

    op = openProtocol.createClient(port, ip, options, (data) => {
        console.log('Connected');
        setupCommands(op, pset, number_screw);
    });

    return op;
};

const setupCommands = (op, pset, number_screw) => {
    op.command("abortJob");
    op.command("selectPset", { payload: { parameterSetID:pset } }, (err) => {

        if (err) {
            return console.log("Fail on selectPset", err);
        }
        
        op.command('setPsetBatchSize', { payload: {parameterSetID: pset, batchSize: number_screw} }, (err, data) => {
            if (err) {
                return console.error('Error in setPsetBatchSize:', err);
            }
            enableTool(op);
        });
    })


};

const enableTool = (op) => {
    op.command("disableTool", (err, data) => {
        if (err) {
            return console.log("Fail on disableTool", err);
        }
        op.command("enableTool", (err, data) => {
            if (err) {
                return console.error("Error in enableTool:", err);
            }

            subscribeLastTightening(op); // Subscribe to the lastTightening event after enabling the tool
        });
    })
};

const subscribeLastTightening = (op) => {
    op.on("lastTightening", (midData) => {
        console.log("Received data on subscribe", midData);

        if(midData.payload.batchCounter === 1 && midData.payload._batchStatus === 1) {
            lastVissageData = null; // Reset the last tightening data after the first screw has been tightened
        }
        
        lastVissageData = midData;
        updateProductionData(op, idProductionData, midData.payload);
    });

    op.subscribe("lastTightening", (err, data) => {
        if (err) {
            console.error("Error subscribing to 'lastTightening':", err);
            return;
        }

        console.log("Subscribed to 'lastTightening'");
        console.log("Data received on subscribe", data);

    })
};

exports.changePset = (req, res) => {
    const { ip, port, pset, number_screw, id } = req.query;
    idProductionData = id;
    connectToServer(ip, port, pset, number_screw); // Connect to the controller
};

exports.latestScrewing = (req, res) => {
    try {
        if (lastVissageData) {
            res.json(lastVissageData);
        } else {
            res.status(204).send("Waiting"); // 
        }
    } catch (error) {
        console.error("Error :", error);
        res.status(500).send("An error occurred while processing the request.");
    }
};

exports.resetScrewingData = (req, res) => {

    if (op) { // Vérifier si op est défini
        console.log('Closing connection...');
        //op.close();
        /*op.command("disableTool", (err, data) => {
            if (err) {
                return console.error('Error in disableTool:', err);
            }
            console.log('Tool disabled');

            op.command("abortJob", (err, data) => {
                if (err) {
                    return console.error('Error in abortJob:', err);
                }
                console.log('Job aborted');

                op.command("communicationStop", (err, data) => {
                    if (err) {
                        return console.error('Error in communicationStop:', err);
                    }
                    console.log('Communication stopped');*/

                    op.command("disconnectTool", (err, data) => {
                        if (err) {
                            return console.error('Error in disconnect:', err);
                        }
                        console.log('Connection closed');
                    });
                /*});
            });
        });*/
    } else {
        console.log('Connection already closed or not established');
        res.status(400).send("Connection already closed or not established");
    }

    lastVissageData = null;
    idProductionData = null;
    res.send(true);
};```

Do you have any solutions ?

**Comment by martybertrand** [comment]
I also get this error when launching my 6th command.

`Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
Emitted 'error' event on SessionControlClient instance at:
    at Socket.<anonymous>`
